### ISSUE TITLE
download hornet snapshot DB - 404 Error

### ISSUE THREAD

**Issue by firesurf** [nuriel77/hornet-playbook#22]
Just tried to do the install and got this:

`TASK [download hornet snapshot DB (can take a while)] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/var/lib/hornet/snapshot/export.bin", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://ls.manapotion.io/export.bin"}`

[https://ls.manapotion.io/export.bin](https://ls.manapotion.io/export.bin)
is down.

**Comment by nuriel77** [comment]
@firesurf thanks for reporting. I've changed the default link https://github.com/nuriel77/hornet-playbook/commit/1d0d5a0cdaa05eb7f6c8fa51d993d513f263b850
You can try a reinstall.
