### ISSUE TITLE
Out of Hosts. I cant get past this issue. 

### ISSUE THREAD

**Issue by ssw22** [nuriel77/hornet-playbook#24]
██╗  ██╗ ██████╗ ██████╗ ███╗   ██╗███████╗████████╗
██║  ██║██╔═══██╗██╔══██╗████╗  ██║██╔════╝╚══██╔══╝
███████║██║   ██║██████╔╝██╔██╗ ██║█████╗     ██║
██╔══██║██║   ██║██╔══██╗██║╚██╗██║██╔══╝     ██║
██║  ██║╚██████╔╝██║  ██║██║ ╚████║███████╗   ██║
╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝

          _|                      _|                            _|
_|_|_|    _|    _|_|_|  _|    _|  _|_|_|      _|_|      _|_|    _|  _|
_|    _|  _|  _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  _|_|
_|    _|  _|  _|    _|  _|    _|  _|    _|  _|    _|  _|    _|  _|  _|
_|_|_|    _|    _|_|_|    _|_|_|  _|_|_|      _|_|      _|_|    _|    _|
_|                            _|
_|                        _|_|

Welcome to HORNET IOTA FullNode Installer!
1. By pressing 'y' you agree to install the HORNET fullnode on your system.
2. By pressing 'y' you aknowledge that this installer requires a CLEAN operating system
   and may otherwise !!!BREAK!!! existing software on your server.
3. If you already have a configured server, re-running this script will overwrite previous configuration.

Ensuring no package managers ...

Updating system packages...
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Check reboot required...
Installing Ansible and git...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.98.9.3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
'universe' distribution component is already enabled for all sources.
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 https://download.docker.com/linux/ubuntu focal InRelease              
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease           
Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Fetched 210 kB in 1s (280 kB/s)                                     
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'expect' instead of 'expect-dev'
cracklib-runtime is already the newest version (2.9.6-3.2).
git is already the newest version (1:2.25.1-1ubuntu3).
libcrack2 is already the newest version (2.9.6-3.2).
whiptail is already the newest version (0.52.21-4ubuntu2).
ansible is already the newest version (2.9.6+dfsg-1).
expect is already the newest version (5.45.4-2build1).
tcl is already the newest version (8.6.9+1).
python3-pip is already the newest version (20.0.2-5ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: jmespath in /usr/lib/python3/dist-packages (0.9.4)
Verifying Ansible version...
Git cloning hornet-playbook repository...
Backing up older hornet-playbook directory...
Cloning into 'hornet-playbook'...
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 1581 (delta 15), reused 32 (delta 13), pack-reused 1537
Receiving objects: 100% (1581/1581), 466.90 KiB | 3.36 MiB/s, done.
Resolving deltas: 100% (854/854), done.

Running playbook...
SSH port to use: 22
*** Running playbook command: ansible-playbook -i inventory -v site.yml -e memory_autoset=true  --skip-tags=_
Using /etc/ansible/ansible.cfg as config file

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Check ansible version >=2.8.0] *******************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [install local dependencies] **********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [install local dependencies] **********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [install gilt] ************************************************************
ok: [localhost] => {"changed": false, "cmd": ["/usr/bin/pip3", "install", "python-gilt"], "name": ["python-gilt"], "requirements": null, "state": "present", "stderr": "", "stderr_lines": [], "stdout": "Requirement already satisfied: python-gilt in /usr/local/lib/python3.8/dist-packages (1.2.3)\nRequirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from python-gilt) (5.3.1)\nRequirement already satisfied: fasteners in /usr/lib/python3/dist-packages (from python-gilt) (0.14.1)\nRequirement already satisfied: colorama in /usr/lib/python3/dist-packages (from python-gilt) (0.4.3)\nRequirement already satisfied: sh in /usr/local/lib/python3.8/dist-packages (from python-gilt) (1.14.1)\nRequirement already satisfied: click in /usr/lib/python3/dist-packages (from python-gilt) (7.0)\n", "stdout_lines": ["Requirement already satisfied: python-gilt in /usr/local/lib/python3.8/dist-packages (1.2.3)", "Requirement already satisfied: PyYAML in /usr/lib/python3/dist-packages (from python-gilt) (5.3.1)", "Requirement already satisfied: fasteners in /usr/lib/python3/dist-packages (from python-gilt) (0.14.1)", "Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from python-gilt) (0.4.3)", "Requirement already satisfied: sh in /usr/local/lib/python3.8/dist-packages (from python-gilt) (1.14.1)", "Requirement already satisfied: click in /usr/lib/python3/dist-packages (from python-gilt) (7.0)"], "version": null, "virtualenv": null}

TASK [run gilt overlay] ********************************************************
ok: [localhost] => {"changed": false, "cmd": ["/usr/local/bin/gilt", "--config", "gilt.yml", "overlay"], "delta": "0:00:01.428675", "end": "2021-01-12 15:26:29.507710", "rc": 0, "start": "2021-01-12 15:26:28.079035", "stderr": "", "stderr_lines": [], "stdout": "nuriel77.ansible-docker:\n  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-docker to /opt/hornet-playbook/roles/docker/\nnuriel77.ansible-haproxy-iota:\n  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-haproxy-iota to /opt/hornet-playbook/roles/haproxy/\nnuriel77.ansible-nginx:\n  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-nginx to /opt/hornet-playbook/roles/nginx/\nnuriel77.ansible-monitoring:\n  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-monitoring to /opt/hornet-playbook/roles/monitoring/", "stdout_lines": ["nuriel77.ansible-docker:", "  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-docker to /opt/hornet-playbook/roles/docker/", "nuriel77.ansible-haproxy-iota:", "  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-haproxy-iota to /opt/hornet-playbook/roles/haproxy/", "nuriel77.ansible-nginx:", "  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-nginx to /opt/hornet-playbook/roles/nginx/", "nuriel77.ansible-monitoring:", "  - extracting (master) /root/.gilt/clone/github.com/nuriel77.ansible-monitoring to /opt/hornet-playbook/roles/monitoring/"]}

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [common : stop if no systemd support] *************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [common : stop if unknown distribution] ***********************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [common : stop if memory is too small] ************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [common : stop if architecture is not supported] **************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [fullnode] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [include playbook roles] **************************************************

TASK [docker : set_fact] *******************************************************
ok: [localhost] => {"ansible_facts": {"server_arch": "amd64"}, "changed": false}

TASK [docker : Ensure dependencies are installed] ******************************
ok: [localhost] => {"cache_update_time": 1610483193, "cache_updated": true, "changed": false}

TASK [docker : Add Docker apt key] *********************************************
ok: [localhost] => {"changed": false}

TASK [docker : Ensure curl is present (on older systems without SNI).] *********
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Add Docker apt key (alternative for older systems without SNI).] ***
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : architecture override repository configuration] *****************
ok: [localhost] => {"ansible_facts": {"docker_apt_repository": "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"}, "changed": false}

TASK [docker : ensure old line with edge is gone] ******************************
ok: [localhost] => {"backup": "", "changed": false, "found": 0, "msg": ""}

TASK [docker : ensure old bionic removed for focal] ****************************
ok: [localhost] => {"backup": "", "changed": false, "found": 0, "msg": ""}

TASK [docker : Add Docker repository.] *****************************************
ok: [localhost] => {"changed": false, "repo": "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable", "state": "present"}

TASK [docker : Install epel-release] *******************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Install some packages] ******************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Add Docker GPG key] *********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Add Docker repository.] *****************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Configure Docker repository] ************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Configure Docker Test repository] *******************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : package] ********************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : get docker script] **********************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : run get docker script, please wait...] **************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : add user pi to docker group] ************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : rasbpian override repository configuration] *********************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : update packages] ************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Install Docker Debian/Ubuntu ...] *******************************
ok: [localhost] => {"cache_update_time": 1610483193, "cache_updated": false, "changed": false}

TASK [docker : Install Docker Centos 7 ...] ************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : Install Docker Centos 8 ...] ************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [docker : ensure docker directory exists] *********************************
ok: [localhost] => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "owner": "root", "path": "/etc/docker", "size": 4096, "state": "directory", "uid": 0}

TASK [docker : add docker configuration] ***************************************
ok: [localhost] => {"changed": false, "checksum": "e7c7919d173079733c3b18e51100f9f0082fb4eb", "dest": "/etc/docker/daemon.json", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "path": "/etc/docker/daemon.json", "size": 53, "state": "file", "uid": 0}

TASK [docker : Ensure Docker is started and enabled] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=0    unreachable=0    failed=1    skipped=18   rescued=0    ignored=0

**Comment by nuriel77** [comment]
@ssw22 in which distribution and version did you install?
Was there anything installed beforehand? (Is this a VPS from a hosting provider?)

**Comment by ssw22** [comment]
Testing on a vm. 
Ubuntu 20.04

I ran the following first:
sudo -- sh -c 'apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y; apt-get autoclean -y'

**Comment by nuriel77** [comment]
Hmm, I tried an installation on a new node on hetzner (ubnutu 20.04) and seems to work fine:
```
TASK [docker : Ensure Docker is started and enabled] *********************************************************************************************************************
ok: [localhost] => {"changed": false, "enabled": true, "name": "docker", "state": "started", "status": ...
```

**Comment by nuriel77** [comment]
For reference, kernel:
```
# uname -r
5.4.0-60-generic
```

**Comment by nuriel77** [comment]
There has been a similar issue to yours reported several months ago on fedora and ubuntu, e.g. https://github.com/ansible/ansible/issues/71528#issuecomment-702608860

**Comment by ssw22** [comment]
So I got farther. How do I troubleshoot this. I can login but no data in dashboard.

**Comment by nuriel77** [comment]
Can you share a screenshot?
Which browser? (did you try other browsers?)

**Comment by ssw22** [comment]
Safari—will try others.

**Comment by ssw22** [comment]
Works on Firefox. All good.

**Comment by ssw22** [comment]
One last question. How do I add the node to trinity wallet I setup . What is the format?

**Comment by nuriel77** [comment]
You have to enable HTTPS via the command line tool `horc` and request for a SSL certificate.
Once you have that you can connect to `https://node-name:14267`

**Comment by ssw22** [comment]
thanks. Awesome. Hornet is cool.

**Comment by ssw22** [comment]
Any neighbors I can add to keep hornet mode in sync? How do I publish node to help ?i  Set it up in azure with monthly credits.

**Comment by nuriel77** [comment]
Check #nodesharing channel on Discord
And for further assitence on hornet #hornet channel on Discord
