### ISSUE TITLE
No sync

### ISSUE THREAD

**Issue by Torgalide** [nuriel77/hornet-playbook#31]
Hello.
I run a fresh new install on VPS 4cpu/8gb.
Install run perfect but not sync. Stuck on 5120 / 15460 (CMI / LMI)
I've sync peers connected.
Any idea?

**Comment by nuriel77** [comment]
@Torgalide Sorry, no idea. Could you try to seek help on #hornet-discussion channel on Discord? Maybe others have the same experience.

**Comment by Iven83** [comment]
I have installed the playbook 5 times, but it never synced or find peers.

**Comment by nuriel77** [comment]
@Iven83 what do you mean by find peers?
As far as I know the autopeering feature from hornet was removed, and all peering is done manually now.

**Comment by Torgalide** [comment]
Still not synced. For peer you need to find some on #nodesharing on iota discord channel

**Comment by nuriel77** [comment]
> For peer you need to find some on #nodesharing on iota discord channe

Exactly. That's why I wondered when you said:

>  but it never synced or find peers.

**Comment by Iven83** [comment]
Ok i thought that autopeering is a feature of hornet. Why it was removed? That make no sense. But thank you for the Information.

**Comment by nuriel77** [comment]
I think they are working on it. Probably they wanted to move forward with CH2 release and will add it later.
You're welcome.

**Comment by Torgalide** [comment]
How can I know what config file hornet is using?

**Comment by nuriel77** [comment]
If you're on the playbook hornet node, you can view the file in `/var/lib/hornet/config.json`

**Comment by Torgalide** [comment]
yes sure thx

**Comment by Iven83** [comment]
Now i have a peer and it runs like a charm. Thanks again

**Comment by Torgalide** [comment]
Ok solve sync problem by delete db and snapshot folder and restart node.
Thx Nuriel77 for your time and work.
