### ISSUE TITLE
No data in Grafana

### ISSUE THREAD

**Issue by Torgalide** [nuriel77/hornet-playbook#32]
Just to let you know that there is no data in grafana for Hornet

**Comment by nuriel77** [comment]
Thanks, haven't gotten there yet.

**Comment by nuriel77** [comment]
Some community members are working on a new dashboard for hornet/grafana. Once it is released I will add it.

**Comment by nuriel77** [comment]
Was added back in June https://github.com/nuriel77/ansible-monitoring/commit/6006ae9966b9ec3b35e1b021bbdddfac8bade2a2
