### ISSUE TITLE
ERROR! the role 'haproxy' was not found 

### ISSUE THREAD

**Issue by uk10904** [nuriel77/hornet-playbook#34]
Installation fails shortly after the username/password step
ERROR! the role 'haproxy' was not found in /opt/hornet-playbook/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/opt/hornet-playbook

-----LOG----
*** Running playbook command: ansible-playbook -i inventory -v site.yml -e memory_autoset=true  --skip-tags=_,loadbalancer_role
^[[0;34mUsing /etc/ansible/ansible.cfg as config file^[[0m
^[[0;34m^[[0m
PLAY [localhost] ********************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
^[[0;32mok: [localhost]^[[0m
^[[0;32m^[[0m
TASK [Check ansible version >=2.8.0] ************************************************************************************************************************************************************
^[[0;32mok: [localhost] => {^[[0m
^[[0;32m    "changed": false,^[[0m
^[[0;32m    "msg": "All assertions passed"^[[0m
^[[0;32m}^[[0m
^[[0;32m^[[0m
TASK [install local dependencies] ***************************************************************************************************************************************************************
^[[0;36mskipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}^[[0m
^[[0;36m^[[0m
TASK [install local dependencies] ***************************************************************************************************************************************************************
^[[0;36mskipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False"}^[[0m
^[[0;36m^[[0m
TASK [install gilt] *****************************************************************************************************************************************************************************
^[[0;33mchanged: [localhost] => {"changed": true, "cmd": ["/usr/bin/pip3", "install", "python-gilt"], "name": ["python-gilt"], "requirements": null, "state": "present", "stderr": "", "stderr_l>
^[[0;33m^[[0m
TASK [run gilt overlay] *************************************************************************************************************************************************************************
^[[0;32mok: [localhost] => {"changed": false, "cmd": ["/usr/local/bin/gilt", "--config", "gilt.yml", "overlay"], "delta": "0:00:03.625583", "end": "2021-05-01 05:56:25.274179", "rc": 0, "start>
^[[0;32m^[[0m
PLAY [all] **************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
^[[0;32mok: [localhost]^[[0m
^[[0;32m^[[0m
TASK [common : stop if no systemd support] ******************************************************************************************************************************************************
^[[0;32mok: [localhost] => {^[[0m
^[[0;32m    "changed": false,^[[0m
^[[0;32m    "msg": "All assertions passed"^[[0m
^[[0;32m}^[[0m
^[[0;32m^[[0m
TASK [common : stop if unknown distribution] ****************************************************************************************************************************************************
^[[0;32mok: [localhost] => {^[[0m
^[[0;32m    "changed": false,^[[0m
^[[0;32m    "msg": "All assertions passed"^[[0m
^[[0;32m}^[[0m
^[[0;32m^[[0m
TASK [common : stop if memory is too small] *****************************************************************************************************************************************************
^[[0;32mok: [localhost] => {^[[0m
^[[0;32m    "changed": false,^[[0m
^[[0;32m    "msg": "All assertions passed"^[[0m
^[[0;32m}^[[0m
^[[0;32m^[[0m
TASK [common : stop if architecture is not supported] *******************************************************************************************************************************************
^[[0;32mok: [localhost] => {^[[0m
^[[0;32m    "changed": false,^[[0m
^[[0;32m    "msg": "All assertions passed"^[[0m
^[[0;32m}^[[0m
^[[0;32m^[[0m
PLAY [fullnode] *********************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************
^[[0;32mok: [localhost]^[[0m
^[[0;32m^[[0m
TASK [include playbook roles] *******************************************************************************************************************************************************************
^[[0;31mERROR! the role 'haproxy' was not found in /opt/hornet-playbook/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/opt/hornet-playbook^[[0m
^[[0;31m^[[0mPLAY RECAP **************************************************************************************************************************************************************************************
^[[0;33mlocalhost^[[0m                  : ^[[0;32mok=10  ^[[0m ^[[0;33mchanged=1   ^[[0m unreachable=0    failed=0    ^[[0;36mskipped=2   ^[[0m rescued=0    ignored=0

**Comment by nuriel77** [comment]
Hi, this should be fixed now, can you try to re-run please?

**Comment by uk10904** [comment]
Hi, This is fixed now and working.  Thanks!
