### ISSUE TITLE
TASK [build hornet image] Failure

### ISSUE THREAD

**Issue by MightySkink** [nuriel77/hornet-playbook#45]
Spent most of the day trying to work out whats going wrong but frankly im hitting a dead end as my knowledge isn't great but I am pretty persistant. 

Any help with this would be much apreciated.

TASK [build hornet image, this can take a moment...] ********************************************************************************************************
FAILED - RETRYING: build hornet image, this can take a moment... (3 retries left).
FAILED - RETRYING: build hornet image, this can take a moment... (2 retries left).
FAILED - RETRYING: build hornet image, this can take a moment... (1 retries left).
**An exception occurred during task execution. To see the full traceback, use -vvv. The error was: docker.errors.APIError: 500 Server Error for http+docker://l                                                                                                                                                                ocalhost/v1.41/build?t=gohornet%2Fhornet%3A1.0.5&q=False&nocache=False&rm=True&forcerm=True&pull=False&dockerfile=docker%2FDockerfile.arm64&buildargs=%7B%22T                                                                                                                                                                AG%22%3A+%221.0.5%22%2C+%22ARCH%22%3A+%22ARM64%22%7D&networkmode=host: Internal Server Error ("Cannot locate specified Dockerfile: docker/Dockerfile.arm64")
fatal: [localhost]: FAILED! => {"attempts": 3, "changed": false, "msg": "An unexpected docker error occurred: 500 Server Error for http+docker://localhost/v1                                                                                                                                                                .41/build?t=gohornet%2Fhornet%3A1.0.5&q=False&nocache=False&rm=True&forcerm=True&pull=False&dockerfile=docker%2FDockerfile.arm64&buildargs=%7B%22TAG%22%3A+%2                                                                                                                                                                21.0.5%22%2C+%22ARCH%22%3A+%22ARM64%22%7D&networkmode=host: Internal Server Error (\"Cannot locate specified Dockerfile: docker/Dockerfile.arm64\")"}**

**Comment by nuriel77** [comment]
ARM architecture not supported at the moment. Sorry, didn't update the readme.
