### ISSUE TITLE
Ubuntu 20.04: usermod: user hornet is currently used by process 3271

### ISSUE THREAD

**Issue by jeliasson** [nuriel77/hornet-playbook#50]
Running the installation script on a Ubuntu 20.04 server gave this error;

```
[...]

TASK [hornet : get release tag] ****************************************************************************************
ok: [localhost] => {"ansible_facts": {"hornet_tag": "1.1.3"}, "changed": false}

TASK [hornet : clone hornet repository] ********************************************************************************
changed: [localhost] => {"after": "1d93f0b7615d45a273889e357ee6b59121768556", "before": null, "changed": true}

TASK [hornet : add user to run hornet as] ******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "usermod: user hornet is currently used by process 32713\n", "name": "hornet", "rc": 8}

NO MORE HOSTS LEFT *****************************************************************************************************

PLAY RECAP *************************************************************************************************************
localhost                  : ok=44   changed=19   unreachable=0    failed=1    skipped=32   rescued=0    ignored=0

ERROR! The playbook exited with failure(s). A log has been save here '/var/log/hornet-playbook-202201252144.log'
```

Running the command as root yields the same error.

This machine has two accounts before running the installation script, namely `ops` on id `1000` and `ansible` on id `9999` (this machine is in fact managed by Ansible). I do not believe these are a result of the ansible-playbook, but I might be wrong.

Ideas?

**Comment by nuriel77** [comment]
Looks like you've somehow ended up already having user hornet on your system not created by the hornet-playbook.
Did you run any other installers previously?

Check process ID 32713 as shown in the error line.

**Comment by jeliasson** [comment]
> Did you run any other installers previously?

Not that I know of, but I'll re-create the server later in the week to see if there is something pre-installation that is/was conflicting.

**Comment by jeliasson** [comment]
@nuriel77 A semi-fresh installation seems to have done the trick. I'll reopen the issue if I see it again. Thanks for a nice playbook! 

Btw, any thought on making the playbook runnable from another Ansible node? In my case, a command-and-control node. Thanks!
