### ISSUE TITLE
No key.pub

### ISSUE THREAD

**Issue by hackicodi** [nuriel77/hornet-playbook#54]
Hello,
What is meant with that issue and how to fix?

 ` systemctl stop hornet && docker run -u 39999:39999 --rm -it -v /var/lib/hornet/p2p:/app/p2p gohornet/hornet:1.0.2 --p2p.peerStore.path=/app/p2p/store tool jwt-api && systemctl start hornetpanic: unable to read public key identity file: open /app/p2p/store/key.pub: no such file or directory`

**Comment by nuriel77** [comment]
Where did you find the above command?

**Comment by hackicodi** [comment]
At your README

**Comment by nuriel77** [comment]
@hackicodi its out-dated. I believe it was removed a while back on hornet

**Comment by hackicodi** [comment]
Ok, but how to get the jwt?

**Comment by nuriel77** [comment]
@hackicodi I've updated the command: https://github.com/nuriel77/hornet-playbook#get-jwt-token

Thanks for opening the issue.
